### ISSUE TITLE
Lack of error handling for user flags

### ISSUE THREAD

**Issue by zredrum** [NTMNathan/discord-dashboard#2]
**Issue:**
"TypeError: Cannot read property 'toArray' of null"
Line 47, master/routes/dashboard.js
File in question: https://github.com/NTMNathan/discord-dashboard/blob/master/routes/dashboard.js

**How to reproduce:**
Visit the dashboard & login process.

**Possible fix:**
Enforce error handling for this specific function. If/else loop in the event it can't find any user badges, as it's likely not everyone has those in the defined "flags" list.

**Comment by zredrum** [comment]
Here's a user example of logs:
![Console Example](https://i.imgur.com/s4husS1.png)

**Comment by NTMNathan** [comment]
Can confirm that I am experiencing this on an account without flags. Doesn't affect users who already have flags so I've applied the patch to fix that bug.

Also the Flags Row in the Table was not there I noticed, thats also added as well. Thanks for the report 😄
